- name: Deploy the Retail Pricing System
  hosts: localhost
  become: true
  vars:
    container_name: "{{ 'retail-pricing-system-production' if env == 'production' else 'retail-pricing-system' }}"
    host_port: "{{ 8502 if env == 'production' else 8501 }}"

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip

    - name: Test Docker CLI Access
      shell: docker ps
      register: docker_test
      ignore_errors: yes

    - name: Print Docker Test Result
      debug:
        msg: "{{ docker_test.stderr | default('Docker is accessible') }}"

    - name: Remove existing container if running
      shell: |
        docker rm -f {{ container_name }} || echo "No existing container to remove"
      args:
        executable: /bin/bash

    - name: Build Docker image locally
      shell: docker build -t retail-price-optimizer -f /app/Dockerfile .
      args:
        chdir: /app

    - name: Run the Docker container
      shell: >
        docker run -d --name {{ container_name }}
        -p {{ host_port }}:8501
        retail-price-optimizer
