- name: Deploy the Retail Pricing System
  hosts: localhost
  become: true
  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
      become: true

    - name: Ensure user is part of the Docker group
      shell: usermod -aG docker $USER
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Refresh group memberships
      shell: newgrp docker || true
      args:
        executable: /bin/bash

    - name: Test Docker CLI Access
      shell: docker ps

    - name: Remove existing container if running
      shell: |
        docker rm -f retail-pricing-system || echo "No existing container to remove"
      args:
        executable: /bin/bash

    - name: Build Docker image locally
      shell: docker build -t retail-price-optimizer -f ../Dockerfile .
      args:
        chdir: "{{ playbook_dir }}"

    - name: Run the Docker container
      shell: >
        docker run -d --name retail-pricing-system
        -p 8080:8080
        retail-price-optimizer
