- name: Deploy the Retail Pricing System
  hosts: localhost
  become: true
  tasks:
    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: true

    - name: Ensure Docker command is available
      command: which docker
      register: docker_check
      failed_when: docker_check.rc != 0

    - name: Remove existing container if running
      shell: |
        docker rm -f retail-pricing-system || echo "No existing container to remove"
      args:
        executable: /bin/bash

    - name: Build Docker image locally
      shell: docker build -t retail-price-optimizer .
      args:
        chdir: "{{ playbook_dir }}"

    - name: Run the Docker container
      shell: >
        docker run -d --name retail-pricing-system
        -p 8080:8080
        retail-price-optimizer
