- name: Deploy the Retail Pricing System
  hosts: localhost
  become: true
  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
      become: true

    - name: Skip starting Docker service since it is already running on host
      debug:
        msg: "Skipping Docker service management since Docker is running on the host"

    - name: Remove existing container if running
      shell: |
        docker rm -f retail-pricing-system || echo "No existing container to remove"
      args:
        executable: /bin/bash

    - name: Build Docker image locally
      shell: docker build -t retail-price-optimizer -f ../Dockerfile .
      args:
        chdir: "{{ playbook_dir }}"

    - name: Run the Docker container
      shell: >
        docker run -d --name retail-pricing-system
        -p 8080:8080
        retail-price-optimizer
