- name: Set up environment for Retail Pricing System
  hosts: localhost
  become: true
  tasks:
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker and dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - python3
        - python3-pip

    - name: Install required Python packages
      pip:
        name: "{{ item }}"
      with_items:
        - ansible
        - docker

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
